export const SUBMIT_TRANSFER_REQUEST = "SUBMIT_TRANSFER_REQUEST";
export const SUBMIT_TRANSFER_SUCCESS = "SUBMIT_TRANSFER_SUCCESS";
export const SUBMIT_TRANSFER_FAILURE = "SUBMIT_TRANSFER_FAILURE";

export const SUBMIT_TRANSFER_GUEST_REQUEST = "SUBMIT_TRANSFER_GUEST_REQUEST";
export const SUBMIT_TRANSFER_GUEST_SUCCESS = "SUBMIT_TRANSFER_GUEST_SUCCESS";
export const SUBMIT_TRANSFER_GUEST_FAILURE = "SUBMIT_TRANSFER_GUEST_FAILURE";



